version: '3.9'

services:
  socket-app:
    container_name: socket-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./:/home
    command: bash -c "npm run build && npm run start"
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGO_INITDB_DATABASE: socket_app

    volumes:
      - ./mongo:/data/db